### ISSUE TITLE
 'Implicit declaration of function' when building on Linux 

### ISSUE THREAD

**Issue by syltensylten** [ComposersDesktop/CDP8#10]
I hope I'm in the right forum for this question, x-post from portaudio. Else let me know and I'll remove. 

When trying to build [CDP8](https://github.com/composersdesktop/cdp8) (uses portaudio) from source using Linux i get the following error message at the very last step.
I built portaudio from source previous to this. Paplay works in cli.

```
[ 99%] Building C object dev/externals/paprogs/paplay/CMakeFiles/paplay.dir/paplay.c.o
/home/user/Downloads/git-clones/CDP8/dev/externals/paprogs/paplay/paplay.c: In function ‘main’:
/home/user/Downloads/git-clones/CDP8/dev/externals/paprogs/paplay/paplay.c:1139:40: error: implicit declaration of function ‘PaUtil_AllocateMemory’; did you mean ‘PaUtil_FreeMemory’? [-Wimplicit-function-declaration]
 1139 |             sfdata.membuf =  (float *) PaUtil_AllocateMemory(nFramesToPlay * sizeof(float) * /*inchans*/ outchans);
      |                                        ^~~~~~~~~~~~~~~~~~~~~
      |                                        PaUtil_FreeMemory
/home/user/Downloads/git-clones/CDP8/dev/externals/paprogs/paplay/paplay.c:1139:30: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 1139 |             sfdata.membuf =  (float *) PaUtil_AllocateMemory(nFramesToPlay * sizeof(float) * /*inchans*/ outchans);
      |                              ^
/home/user/Downloads/git-clones/CDP8/dev/externals/paprogs/paplay/paplay.c:1156:34: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 1156 |             sfdata.ringbufData = (float *) PaUtil_AllocateMemory( ringframelen * sizeof(float) * outchans); /* From now on, recordedSamples is initialised. */
      |                                  ^
/home/user/Downloads/git-clones/CDP8/dev/externals/paprogs/paplay/paplay.c:1173:24: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 1173 |         sfdata.inbuf = (float *) PaUtil_AllocateMemory(ringframelen * sizeof(float) * inchans);
      |                        ^
make[2]: *** [dev/externals/paprogs/paplay/CMakeFiles/paplay.dir/build.make:76: dev/externals/paprogs/paplay/CMakeFiles/paplay.dir/paplay.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:7671: dev/externals/paprogs/paplay/CMakeFiles/paplay.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

``` 
From what i can tell it's an error with the included paplay code at line 1139 where the compiler stumbles upon an error with an incorrect declaration of a function. Is there an actual error in the paplay.c or is there something else that's fishy? 

Please let me know further troubleshooting measures or point me in the direction.
Thanks

**Comment by richarddobson** [comment]
This means the compiler has not found the required header file 
pa_util.h, where those functions are declared. This can happen if, for 
example, portaudio was not unpacked and built where the CDP makefiles 
need it to be as documented (inside directory "paprogs"). We use some 
source files that are not installed publicly by general portaudio 
installers, most particularly in order to make use of the portaudio 
"ringbuffer" code. Strictly speaking the portaudio developers regard 
that as a component internal/private to portaudio, and which in theory 
might be changed without warning. To date that has not happened. But it 
is one reason we need access to that header file via the full source 
distribution.

RD.

**Comment by syltensylten** [comment]
Thank you for taking your time. 
I fetched a previous .h file that it did not find, might try to fetch the pa_util.h file from portaduio repo. Else it sounds like my best option is to reinstall portaudio and make sure the files end up in paprogs. Or i might just copy them there. Or see if i can point the makefile to my local portaudio dir.

Thanks again Richard

**Comment by syltensylten** [comment]
So i moved the pa_util.h file to the paplay folder under paprogs in externals and it compiled!
