### ISSUE TITLE
linux compile error

### ISSUE THREAD

**Issue by ormf** [ComposersDesktop/CDP8#5]
Hi,

trying to compile for arch linux here is what I found:

1. downloading and compiling portaudio in the CDP8 dir (resulting in a correctly populated "CDP8/portaudio/libs/.lib" directory) still gives a cmake error. Installing portaudio systemwide with "sudo make install" works though.
2. a subsequent "cd build && cmake .. && make" will start compiling, but it gets stuck here:

...
[  7%] Linking CXX executable /home/orm/work/install/CDP8/NewRelease/rmsinfo
[  7%] Built target njoin
[  7%] Built target abfdcode
[  7%] Built target abfpan
[  7%] Linking C static library libcdp2k.a
[  7%] Built target abfpan2
[  7%] Built target rmsinfo
[  7%] Built target cdp2k
[  8%] Linking CXX executable /home/orm/work/install/CDP8/NewRelease/fastconv
[  8%] Built target fastconv
[  8%] Linking C executable /home/orm/work/install/CDP8/NewRelease/fmdcode
[  8%] Built target fmdcode
make: *** [Makefile:156: all] Fehler 2

Is there anything I can do to make it work?

**Comment by jpffitch** [comment]
No simple idea without an error message of some kind.  Can you check files like CMakeError.log and CMakeOutput.log?
Weak evidence of it being related to portsf subsystem

**Comment by ormf** [comment]
I found the culprit: I used make with multiple cores simultaneously: Compiling it on a single core works. As a note: IIUC something seems to be missing concerning portaudio: portaudio was compiled in CDP8/portaudio but cmake doesn't find it. I had to install it systemwide and also copy the include files to /usr/local/include before it compiled all the way.

**Comment by ormf** [comment]
Closed as it works.
